# Site settings
title: Michael Blank's Homepage
description: Michael Blank's Homepage
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Blank
user_description: Designing and coding software is what I do and I'm really passionate about it.
user_title: Passionate software developer and architect.
email: mboook@gmail.com
twitter_username: mboook
github_username:  mbok
gplus_username:  mboook

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
